[connections.snowflake]
account = "ve82242"
user = "PHANSIVANG"
password = "ChengPhan$ivang123"        # or use authenticator below
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
# database / schema chosen at runtime in the sidebar